<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input personal</name>
   <tag></tag>
   <elementGuidId>600044c2-bf91-4518-b7d1-7efa66e184ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCustType_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rblCustType_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df75df5a-c98a-4c81-8cf3-fd756c716dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCustType_0</value>
      <webElementGuid>59af376c-7380-46a7-87c1-a3c4f85ef930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f57324ba-4f09-42ba-be2d-b7256d2437fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCustType</value>
      <webElementGuid>1c4262b5-8a84-4d16-8739-8af68e7e602d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>c07c2751-f147-498f-b8c3-34591b6133b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>3371f20d-d197-4426-8f41-7686cc6ae73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCustType_0&quot;)</value>
      <webElementGuid>f59a963d-1329-42f7-8175-42e0256005e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>b4005b93-3db2-4926-8fe7-546abfa9c579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCustType_0']</value>
      <webElementGuid>8fbf9c91-9639-47f7-a647-8ea020787451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCustType']/tbody/tr/td/input</value>
      <webElementGuid>a4eb1d19-3317-4181-aa1f-3e1713835640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7b28ae3b-64a7-4afd-94c6-6a1c73a54232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCustType_0' and @type = 'radio' and @name = 'rblCustType' and @checked = 'checked']</value>
      <webElementGuid>9c480067-a829-46dd-a3b5-a5fdf48a2cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
