<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KTP</name>
   <tag></tag>
   <elementGuidId>c4da7291-2d50-4832-ad54-8279e5770ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucIdCust_txtCustIdNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9a985f-9ac4-4ff1-afb9-63e9382dad62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucIdCust$txtCustIdNo</value>
      <webElementGuid>6ccc7ea3-3580-463c-be89-1ef1e3c9d9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a66c5c5e-c2bf-45ae-9ee5-4ca21f25c286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b7973773-845b-4a9b-b837-82e517a0e7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucIdCust_txtCustIdNo</value>
      <webElementGuid>32f42df3-b8c8-46a6-8e8b-a66bbbef3886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a2fde16e-4833-4daf-a10c-a396ad6545b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtMedInputStyle</value>
      <webElementGuid>69cb5366-f039-472f-921f-330daa9d32cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucIdCust_txtCustIdNo&quot;)</value>
      <webElementGuid>e0cc4f01-99c2-4cf2-a214-c336dbb50bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>752b6d95-38d8-466c-8941-2dd17104caea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      <webElementGuid>5c6eccbb-9454-4a01-a4f7-24e839b212c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoID']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>ca799079-753d-47bc-9079-5cecba0271db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>6554058d-e175-4aa8-a356-52b10c3887f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucIdCust$txtCustIdNo' and @type = 'text' and @id = 'ucIdCust_txtCustIdNo']</value>
      <webElementGuid>af039580-2107-4ea9-88b3-fe19c8828f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
