<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH company</name>
   <tag></tag>
   <elementGuidId>06b20feb-faeb-4f0c-a050-e5e9c9bb044e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65b5b092-ef67-446a-9d2c-5d1f54fce257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>1496a02b-3f54-4bdf-aeda-6c96ff3d26ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>aa584fb4-3ad8-4ce4-ba35-fe22e7565f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>856b9337-67ca-4775-8a79-f93c07ab904c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>5cc9e15e-e9c6-4e94-b154-2d68cac30022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>ba1c9e63-e318-4ac9-9bdf-495179e78380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>b8ca743f-3814-494a-a910-579020686260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>bd816126-101e-4317-b505-3b31ad1b2e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uclCust_uclCust_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>d9f4cc65-48ba-4e81-a365-92cf86867cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH')]</value>
      <webElementGuid>5eb38525-48a3-41d3-b1f6-dbc34c6a5e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::a[1]</value>
      <webElementGuid>f903c1ae-8890-41b6-b1c8-694431670977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/following::a[1]</value>
      <webElementGuid>1564029b-0a43-43ef-9c64-de2b1022ea0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/preceding::a[1]</value>
      <webElementGuid>c43a2c94-8df3-4119-a81a-6f850a3c630d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Model'])[1]/preceding::a[2]</value>
      <webElementGuid>499820a6-f5a9-4555-8da8-af8d3c168f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>01f46275-6bf4-4bc7-8f01-eec1af35822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>ff2cd7db-cd9d-4ca8-8a95-8962c3c6ca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>56e185ba-a1bc-47f8-9e39-25b81f7aa34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>35e54277-fc23-4c7d-ac93-4ab4b662fef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
