<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH customer name company</name>
   <tag></tag>
   <elementGuidId>59b6fb16-6f58-49f9-8896-91d4b25e2158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclCust_uclCust_imb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_imb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45de379b-1a5f-4f3e-a53f-f53b803bc541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>862de689-0628-47a1-a96e-1278b28f6d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclCust$uclCust$imb</value>
      <webElementGuid>c90efcdb-d74b-4bf4-9a64-89005d5ad319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_imb</value>
      <webElementGuid>e1fff72f-002b-4012-8fb2-7a04a75ebc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>24712d0c-52b6-4ffc-bb92-80fc28c4f4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnuclCust_uclCust');</value>
      <webElementGuid>5b5f977f-d11f-43a3-bea0-1ec7b183cbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_imb&quot;)</value>
      <webElementGuid>cb31f874-b7a5-4cab-b5d2-1fd18531529b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>d503dbf4-529a-4597-b5d9-9d49a35d1f5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclCust_uclCust_imb']</value>
      <webElementGuid>de1710bd-cd6b-458c-a923-6561d2948797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trUclCust']/td[2]/ul/li/input[2]</value>
      <webElementGuid>fa2bd8f4-db4a-4d2d-b2a3-bcb1308beaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>0ecb8d3e-0873-490f-875f-9a32782d7ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'uclCust$uclCust$imb' and @id = 'uclCust_uclCust_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>81ff7b54-cf52-477a-89dc-129b2dc3d186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
