<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select personal</name>
   <tag></tag>
   <elementGuidId>a80f170a-293c-4b29-bd9a-f74e3b914c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8d35a7b-2b1f-4725-9ba9-0ca95e811298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>f4df3b1e-1fca-4db7-9510-d193def6b7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','5010000304','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424','uclCust_uclCust_hd7','5830998','uclCust_uclCust_hd8','');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
      <webElementGuid>f13f6f56-6175-4abf-bf0e-56ea7f299e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>4a8aba2b-7060-459d-890c-9a741692e270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>103a88e4-a64c-449d-ad7e-e9f416486d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>26a7e95d-79dc-4d99-9088-e0e6b351feea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>2ad5e417-0f65-41c0-8c52-70bf49ddfdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>883a33f0-4144-4313-8c97-0934f2fa85fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>1954d515-7a04-4ba5-883e-89ca6da6fc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424'])[1]/following::a[1]</value>
      <webElementGuid>a6a1ec0f-5ec5-4d88-a129-7037989d2cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>93dfa1dd-f6a5-490b-acbd-95c2c3207b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>a9a59e5d-8069-430c-95f7-e33eb47c4676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>431a5149-90c0-41a3-9aa5-e42ab16619c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','5010000304','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424','uclCust_uclCust_hd7','5830998','uclCust_uclCust_hd8','');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
      <webElementGuid>5201a8bf-3140-400c-8f56-247194e1b94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>192111df-e003-497b-ba94-e5c8ce3c7f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CustLookup(&quot; , &quot;'&quot; , &quot;uclCust_uclCust_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;HO HENDY&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;5010000304&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;P&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Personal&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;5830998&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>669eb34b-f527-41af-81b3-9ed96ace1023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
