<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select company</name>
   <tag></tag>
   <elementGuidId>1858f555-4e54-4100-9940-c08585ef5d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2d22fa5-5330-4bdf-86f7-3bde57101695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>636ec474-4e4b-48ec-9ae7-c4853164772c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','TEST HO','uclCust_uclCust_hd2','9990000016','uclCust_uclCust_hd3','C','uclCust_uclCust_hd4','Company','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250','uclCust_uclCust_hd7','6601930','uclCust_uclCust_hd8','6601930');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
      <webElementGuid>240c980d-7227-4b2a-97e9-f1b36889f5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>da16d746-3f91-42b9-aa70-5cda9a3e53cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>53cce62c-6a30-4259-8ccb-d5acd66a018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>24a37be1-f74d-404a-a8c6-dcec0ed029c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>2e79c792-4faf-4d72-84e7-2e67d8c0e2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>217b3f71-c447-4aa8-b92d-a0500c045297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>0f9c4958-9aaa-4cc0-a7a6-2bd3afa2f687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250'])[1]/following::a[1]</value>
      <webElementGuid>40ff26a4-4171-429e-844a-2dc88406d0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>321aad9c-ab61-4c21-9e7c-69305aaa53ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>8ca5cfba-b0a1-4909-8047-f3bb56954c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>1dc7fb1f-e0bc-4c2f-8e47-53c687d73883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','TEST HO','uclCust_uclCust_hd2','9990000016','uclCust_uclCust_hd3','C','uclCust_uclCust_hd4','Company','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250','uclCust_uclCust_hd7','6601930','uclCust_uclCust_hd8','6601930');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
      <webElementGuid>c7df4037-1ee7-4f24-827d-b17c189fe674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>5f62f264-afbe-4f9f-93a0-e40519423091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CustLookup(&quot; , &quot;'&quot; , &quot;uclCust_uclCust_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TEST HO&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;9990000016&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;C&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Company&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TEST Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;6601930&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;6601930&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>58e9d7ee-d72f-4cd6-acde-3720d8ce67cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
