<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</name>
   <tag></tag>
   <elementGuidId>70cb16ef-08e2-46b6-8425-1909c1a53c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>32a57353-d97e-4df4-b7a0-5b5599350744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>6374f08d-e890-4a0e-a1f4-d4e34483bcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>f92ebc32-a3b8-408c-9f51-ebace030aadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6caf8e72-ab79-4194-a2ee-a58a2662cdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY</value>
      <webElementGuid>204e6782-5f63-49ed-b9fd-2436e6785565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPage&quot;)</value>
      <webElementGuid>1e42d610-8028-4b73-8d07-e75770693429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainPage']</value>
      <webElementGuid>db50e852-8ce0-4841-8066-93cda203ec1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[3]</value>
      <webElementGuid>dcd19048-53d0-4ce1-bcd6-9d36b0f4bbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>8f839806-e16f-499c-9964-aa59770a8e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainPage' and @name = 'mainPage' and @src = 'LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY']</value>
      <webElementGuid>6c489dfb-0057-49c9-9f8d-b8135c323967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
