<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sreach Product Offering Name</name>
   <tag></tag>
   <elementGuidId>dea7e39a-97be-40b9-a421-1a974d5a41a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_imb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e434e4-1695-4ec2-aecd-24d2deb16822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>f1f2cd92-a7d7-4183-a0a7-ebccb27cb635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupProdOffer$uclProductOffering$imb</value>
      <webElementGuid>e79da77f-2bc1-4904-ad00-6bcee849142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_imb</value>
      <webElementGuid>def8a780-6b48-4a00-8bd0-ebc53d2dfca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>0b43753a-d99d-4149-9c19-0008b143d933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupProdOffer_uclProductOffering');</value>
      <webElementGuid>1afb61c9-61e3-4ffb-bec0-d49b7d508759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_imb&quot;)</value>
      <webElementGuid>075121ff-19f1-43d3-9a12-28fb5f09a0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Add New Application Motor/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>a471882e-9d10-449c-b26d-dd931f43ef84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupProdOffer_uclProductOffering_imb']</value>
      <webElementGuid>003abf34-8e81-4707-a64e-e0b098a85ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table/tbody/tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>a5856077-68cd-4f3b-9010-436cd5556fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>ffdaf410-7bc2-4a77-8d15-886d7368fcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupProdOffer$uclProductOffering$imb' and @id = 'ucLookupProdOffer_uclProductOffering_imb' and @src = '../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>c851c5d9-0661-482f-8a5f-a7831ec80c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
