<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuPadding</name>
   <tag></tag>
   <elementGuidId>38f8c9a1-cd6c-4638-b1f6-116a8d854900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dMenuPadding']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dMenuPadding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1624dc1-7810-4a7d-82c8-fed821e7c5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dMenuPadding</value>
      <webElementGuid>43be2d69-a9da-4cef-9b34-a11ed70701cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dMenuPadding&quot;)</value>
      <webElementGuid>c8369532-cb8b-440e-a955-b02afd00a50e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dMenuPadding']</value>
      <webElementGuid>aa03f3df-d492-40fa-a01c-967a161e9c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='toggleLink']/div</value>
      <webElementGuid>63dd5341-9542-490a-b972-356691a9e452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, Anita Gusti, KEDOYA, Credit Admin'])[1]/following::div[3]</value>
      <webElementGuid>cc0ae49e-485d-4496-8448-bcc13ed5e6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday, 06 February 2024'])[1]/following::div[3]</value>
      <webElementGuid>208c36bc-0e85-4c16-ab36-a6f65522f24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © AdIns 2011. All Right Reserved'])[1]/preceding::div[2]</value>
      <webElementGuid>3414a1fd-146c-4dfc-b275-57ce878d69d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification'])[1]/preceding::div[3]</value>
      <webElementGuid>3e6da2ea-05bd-413b-bd9e-9ca5b5eb4a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>0087e7d2-f602-4488-89cc-fb55764d15e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dMenuPadding']</value>
      <webElementGuid>cfa02ac3-793b-457f-8459-ccb775316f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
