<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8 Select</name>
   <tag></tag>
   <elementGuidId>c7575c8b-bea8-4085-bb37-f2aa68006ab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:OfficeEmpLookup('uclOfficeEmp1_uclOfficeEmp_txt','uclOfficeEmp1_uclOfficeEmp_hd1','Ho Hendy','uclOfficeEmp1_uclOfficeEmp_hd2','IT QUALITY ASSURANCE UNIT HEAD','uclOfficeEmp1_uclOfficeEmp_hd3','Head Office','uclOfficeEmp1_uclOfficeEmp_hd4','2122','uclOfficeEmp1_uclOfficeEmp_hd5','237','uclOfficeEmp1_uclOfficeEmp_hd6','1');;overlay('mdnuclOfficeEmp1_uclOfficeEmp');__doPostBack('mdnuclOfficeEmp1_uclOfficeEmp', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MOU DOC SIGN/iframe_Welcome, REY PUTRANTO, JAKARTA RETAIL, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclOfficeEmp1_uclOfficeEmp_umd_ctl00_gvL']/tbody/tr[2]/td[4]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Head Office'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT QUALITY ASSURANCE UNIT HEAD'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ho Hendy'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT QUALITY ASSURANCE UNIT HEAD'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:OfficeEmpLookup('uclOfficeEmp1_uclOfficeEmp_txt','uclOfficeEmp1_uclOfficeEmp_hd1','Ho Hendy','uclOfficeEmp1_uclOfficeEmp_hd2','IT QUALITY ASSURANCE UNIT HEAD','uclOfficeEmp1_uclOfficeEmp_hd3','Head Office','uclOfficeEmp1_uclOfficeEmp_hd4','2122','uclOfficeEmp1_uclOfficeEmp_hd5','237','uclOfficeEmp1_uclOfficeEmp_hd6','1');;overlay('mdnuclOfficeEmp1_uclOfficeEmp');__doPostBack('mdnuclOfficeEmp1_uclOfficeEmp', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
   </webElementXpaths>
</WebElementEntity>
