<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role user</name>
   <tag></tag>
   <elementGuidId>15d59d39-5f1c-4c45-944f-051b75fffad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uModDRole_ctl00_gvRoles_lbSelectRole_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26ee9fc8-dee4-4e3d-bbb2-1e5c7c688594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('roleOverlay');</value>
      <webElementGuid>5234a7ca-17ac-4b5a-9e18-c2f5bfd574e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uModDRole_ctl00_gvRoles_lbSelectRole_0</value>
      <webElementGuid>2889cbb2-a1c8-481d-a32a-f44a81f282e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl02$lbSelectRole','')</value>
      <webElementGuid>ab81ec64-904e-423b-ac52-621e83235d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>fa1c6788-4433-462a-8fb8-bfdd83cf28bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uModDRole_ctl00_gvRoles_lbSelectRole_0&quot;)</value>
      <webElementGuid>d961dcac-df5d-48ba-ad47-476c5312e2a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_0']</value>
      <webElementGuid>f8d635f0-d926-4ef3-8730-382ca12d6e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uModDRole_ctl00_gvRoles']/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>5a29d259-a966-46e1-b7b0-a6bc42280e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>93b5c7ee-21a6-403c-a019-3072f73e4d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Admin'])[1]/following::a[1]</value>
      <webElementGuid>00a275fe-c1cd-4fe6-b43e-9345bfa1480c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN CREDIT'])[1]/following::a[1]</value>
      <webElementGuid>e9b96ea2-438d-4d9a-bd10-e4beaf768ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PALOPO'])[1]/preceding::a[1]</value>
      <webElementGuid>f60e627b-b4f6-4986-9032-134400613296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN CREDIT'])[2]/preceding::a[1]</value>
      <webElementGuid>2f200c10-d52a-4edf-90f0-31e015bfe2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>35ee188a-3cf6-49ad-8724-9951f51dcb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl02$lbSelectRole','')&quot;)]</value>
      <webElementGuid>339e5b23-7ef8-4ce4-8cfa-206b8efe8620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>14d4853a-7283-4968-b524-c1e055b135c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uModDRole_ctl00_gvRoles_lbSelectRole_0' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;uModDRole$ctl00$gvRoles$ctl02$lbSelectRole&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>49bf9268-1e23-4b7d-9287-2d1f5a23ab3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
