<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Supplier Loan data</name>
   <tag></tag>
   <elementGuidId>bca7eb57-b5ac-4c3e-9134-8fb9debcedf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:SupplBranchSchmLookupX('ucLookupSupplierBranch_uclSupplBranchSchmX_txt','ucLookupSupplierBranch_uclSupplBranchSchmX_hd1','AFRAZ JAYA ABADI MOTOR','ucLookupSupplierBranch_uclSupplBranchSchmX_hd2','84','ucLookupSupplierBranch_uclSupplBranchSchmX_hd3','14761','ucLookupSupplierBranch_uclSupplBranchSchmX_hd4','AFRAZ JAYA ABADI MOTOR','ucLookupSupplierBranch_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplierBranch_uclSupplBranchSchmX_hd6','KEDUNG ANYAR TENGAH NO.7','ucLookupSupplierBranch_uclSupplBranchSchmX_hd7','7/31/2021 12:00:00 AM');;overlay('mdnucLookupSupplierBranch_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplierBranch_uclSupplBranchSchmX', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_New Confins - Main/iframe_Term  Condition_appForm (3)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEDUNG ANYAR TENGAH NO.7'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORMAL'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:SupplBranchSchmLookupX('ucLookupSupplierBranch_uclSupplBranchSchmX_txt','ucLookupSupplierBranch_uclSupplBranchSchmX_hd1','AFRAZ JAYA ABADI MOTOR','ucLookupSupplierBranch_uclSupplBranchSchmX_hd2','84','ucLookupSupplierBranch_uclSupplBranchSchmX_hd3','14761','ucLookupSupplierBranch_uclSupplBranchSchmX_hd4','AFRAZ JAYA ABADI MOTOR','ucLookupSupplierBranch_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplierBranch_uclSupplBranchSchmX_hd6','KEDUNG ANYAR TENGAH NO.7','ucLookupSupplierBranch_uclSupplBranchSchmX_hd7','7/31/2021 12:00:00 AM');;overlay('mdnucLookupSupplierBranch_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplierBranch_uclSupplBranchSchmX', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
