<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>34 Select Supplier branch name</name>
   <tag></tag>
   <elementGuidId>5fa089de-bfca-4928-af63-ff2a2cefa6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1','AGIL MOTOR','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','4','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','4234','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','AGIL MOTOR','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','JL. RAYA CIBANTENG KM 12','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','10/2/2026 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Step 1 New Application/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL. RAYA CIBANTENG KM 12'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORMAL'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1','AGIL MOTOR','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','4','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','4234','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','AGIL MOTOR','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','JL. RAYA CIBANTENG KM 12','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','10/2/2026 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
