<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Customer name</name>
   <tag></tag>
   <elementGuidId>4bcc2bbe-686d-49fa-ae3c-ad946dbbfb80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','9990000008','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','JLN TESTING Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250','uclCust_uclCust_hd7','2983554','uclCust_uclCust_hd8','2983554');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Komponen_Menu_LOS/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JLN TESTING Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','9990000008','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','JLN TESTING Rt.123 Rw.123 JEMBATAN LIMA, TAMBORA, JAKARTA BARAT, 11250','uclCust_uclCust_hd7','2983554','uclCust_uclCust_hd8','2983554');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
