<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Supp ALUZ MOBILINDO</name>
   <tag></tag>
   <elementGuidId>dfe97dc9-c044-42c6-98df-39d2b63bbb3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1','ALUZ MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','10','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','4558','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','ALUZ MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','PERUMAHAN DASANA INDAH BLOK BC 4 NO 1','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','9/12/2021 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Tab Asset Data/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSupplBranchSchm_uclSupplBranchSchmX_umd_ctl00_gvL']/tbody/tr[3]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERUMAHAN DASANA INDAH BLOK BC 4 NO 1'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORMAL'])[3]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM MOTOR TANGERANG'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM MOTOR - TANGERANG'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:SupplBranchSchmLookupX('ucLookupSupplBranchSchm_uclSupplBranchSchmX_txt','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd1','ALUZ MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd2','10','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd3','4558','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd4','ALUZ MOBILINDO','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd6','PERUMAHAN DASANA INDAH BLOK BC 4 NO 1','ucLookupSupplBranchSchm_uclSupplBranchSchmX_hd7','9/12/2021 12:00:00 AM');;overlay('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplBranchSchm_uclSupplBranchSchmX', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
