<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddPersonal Guarantor</name>
   <tag></tag>
   <elementGuidId>723d2d4f-6ef1-4226-8a55-d9e9ceaf3697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_AgrmntGuarantor_AddPersonal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lb_AgrmntGuarantor_AddPersonal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5edd500-1804-4104-961d-ceb89a056e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7675a39d-1039-4aec-901b-61264337cffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_AgrmntGuarantor_AddPersonal</value>
      <webElementGuid>cd8cbc22-19ee-4ea3-9501-517660f1dab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ADD PERSONAL</value>
      <webElementGuid>815c8373-47fd-4521-b2e2-40b51d12d1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_AgrmntGuarantor_AddPersonal&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>eafb0044-6c33-4d6c-8745-038b8ef672d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_AgrmntGuarantor_AddPersonal</value>
      <webElementGuid>f4a54e0e-1b22-4c69-9186-5296a629392e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>6828097d-f8cd-422a-b742-fc361e1b5ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_AgrmntGuarantor_AddPersonal&quot;)</value>
      <webElementGuid>f20a5c32-6fc4-45ac-bd84-0e67118189bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Guarantor/iframe_Term  Condition_appForm</value>
      <webElementGuid>a9331e02-6d6b-46f6-8b16-68f3be65f62c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_AgrmntGuarantor_AddPersonal']</value>
      <webElementGuid>6042bc02-5677-42d9-9bb8-5e541d188bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuAdd']/span/input</value>
      <webElementGuid>c7bbad00-7a59-4a1e-9d0d-e3cf6eef34ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>eaf3092e-cdbf-4cb7-b1e6-fb0e6dab9206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_AgrmntGuarantor_AddPersonal' and @id = 'lb_AgrmntGuarantor_AddPersonal']</value>
      <webElementGuid>6835c10a-982d-41dd-905c-58a262488f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
