<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>klik search Customer Name</name>
   <tag></tag>
   <elementGuidId>372000a3-0021-497e-b77d-901c74678019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupCust_uclCust_imb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCust_uclCust_imb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7d599ae-b314-4da3-9ee2-3db8188a6640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>29194afe-130e-4352-8748-de13e59638be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupCust$uclCust$imb</value>
      <webElementGuid>cb617906-b3d2-4fa6-a1a9-a262cc63d050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCust_uclCust_imb</value>
      <webElementGuid>e0e23e0e-4a15-492e-9622-b976bf762406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>7ce797c4-d586-48b0-b9c4-78911bc9b048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupCust_uclCust');</value>
      <webElementGuid>2a0c57ce-3416-4328-952b-0492e7bbe47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCust_uclCust_imb&quot;)</value>
      <webElementGuid>d8de3464-5b85-4d13-8bf5-7ef4915f6581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Guarantor/iframe_Term  Condition_appForm</value>
      <webElementGuid>627ac3b0-cb89-4e5c-a435-99b1e1b12a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupCust_uclCust_imb']</value>
      <webElementGuid>9ad0e52d-86a1-4ba2-a2a4-cd081b2e4897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>533a82f7-06b9-4f7b-93e2-61029e5b3a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>ec8f07e7-6e27-4320-b35c-b8313dceecaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupCust$uclCust$imb' and @id = 'ucLookupCust_uclCust_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>3638da38-b3c7-490f-82ba-f974b84e5601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
