<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Guarantor</name>
   <tag></tag>
   <elementGuidId>c16aaa63-32af-485c-aa2b-53a85747beaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2127ac4f-6488-48d1-9571-42e1198ae495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>e300f9ef-b744-422d-9507-13f497cf6d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('ucLookupCust_uclCust_txt','ucLookupCust_uclCust_hd1','WANGARATTA','ucLookupCust_uclCust_hd2','023.06.00000003','ucLookupCust_uclCust_hd3','P','ucLookupCust_uclCust_hd4','Personal','ucLookupCust_uclCust_hd5','-','ucLookupCust_uclCust_hd6','APT GDG NIAS RESIDENCES T/12/TC Rt.002 Rw.003 PEGANGSAAN DUA, KELAPA GADING, JAKARTA UTARA, 14250','ucLookupCust_uclCust_hd7','538682','ucLookupCust_uclCust_hd8','538682');;overlay('mdnucLookupCust_uclCust');__doPostBack('mdnucLookupCust_uclCust', '')</value>
      <webElementGuid>d61276fa-cf8d-4966-bc33-d0107fb30276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>7d31acf0-f88c-4cfd-90ec-22d775e2262f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>7e04d60f-a95b-420f-9107-a333d2fd1bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Guarantor/iframe_Term  Condition_appForm</value>
      <webElementGuid>76157238-471b-471b-9a8e-569c7bab1ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>5f274907-2e1a-4d55-b102-688658cc449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>e274eef5-065f-4656-8cf6-81c03d98b1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>0df539dd-7e70-4342-ae72-934113712fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APT GDG NIAS RESIDENCES T/12/TC Rt.002 Rw.003 PEGANGSAAN DUA, KELAPA GADING, JAKARTA UTARA, 14250'])[1]/following::a[1]</value>
      <webElementGuid>7a490dbf-d523-47d8-aad3-9496ff33921b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>aa4011b1-57fc-4785-af20-e2065aa15fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>4243500b-6841-4f53-b90b-e01fb9730deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>eb0a4e63-2a26-4ef0-9f03-bd0ccc13e801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('ucLookupCust_uclCust_txt','ucLookupCust_uclCust_hd1','WANGARATTA','ucLookupCust_uclCust_hd2','023.06.00000003','ucLookupCust_uclCust_hd3','P','ucLookupCust_uclCust_hd4','Personal','ucLookupCust_uclCust_hd5','-','ucLookupCust_uclCust_hd6','APT GDG NIAS RESIDENCES T/12/TC Rt.002 Rw.003 PEGANGSAAN DUA, KELAPA GADING, JAKARTA UTARA, 14250','ucLookupCust_uclCust_hd7','538682','ucLookupCust_uclCust_hd8','538682');;overlay('mdnucLookupCust_uclCust');__doPostBack('mdnucLookupCust_uclCust', '')&quot;)]</value>
      <webElementGuid>4aedc64a-f407-4cf5-883e-67ce87278108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>49372c6d-e4f3-4031-9036-88726faed866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CustLookup(&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;WANGARATTA&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;023.06.00000003&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;P&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Personal&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;APT GDG NIAS RESIDENCES T/12/TC Rt.002 Rw.003 PEGANGSAAN DUA, KELAPA GADING, JAKARTA UTARA, 14250&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;538682&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCust_uclCust_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;538682&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupCust_uclCust&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupCust_uclCust&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6cfc1e64-6918-488b-9ebf-1647b04f6f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
