<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application Number</name>
   <tag></tag>
   <elementGuidId>55c4839c-64c4-4230-b5f4-32e1bc651772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucCreditProcessMainInfo_lbAppNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f3952ff-0ed6-48ba-9a0d-7dae06dbae2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCreditProcessMainInfo_lbAppNo</value>
      <webElementGuid>f01169b0-9ed6-44e3-83c1-3e08e56096f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')</value>
      <webElementGuid>4073ff2c-1d60-40e2-9e0f-0fe94c5ea1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>539APP20240200145</value>
      <webElementGuid>8f057635-9cc7-4c48-b664-0de2717ce127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucCreditProcessMainInfo_lbAppNo&quot;)</value>
      <webElementGuid>cf4eb483-a32c-4ebf-a224-f1f50c5d5597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>62e3f351-a8ae-456a-a3a8-e58d22706e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      <webElementGuid>e0d11fa8-831a-4928-91df-42ad8269aefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainInfoUC']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>b79df62d-863c-44e4-a264-60913d952c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'539APP20240200145')]</value>
      <webElementGuid>74c7965e-9470-4bec-a060-edd502131f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Number'])[1]/following::a[1]</value>
      <webElementGuid>f93605b3-1a04-4e06-a25e-8407bdcddf56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Info'])[1]/following::a[1]</value>
      <webElementGuid>a30614af-6653-4f0e-86e6-d8dcbe8d1a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num Of Asset'])[1]/preceding::a[1]</value>
      <webElementGuid>57b000d9-4068-4f78-942f-e4689bc6ea4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Office'])[1]/preceding::a[1]</value>
      <webElementGuid>9bf7c696-6bf8-4058-b214-ac3b81d672c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='539APP20240200145']/parent::*</value>
      <webElementGuid>c4622181-3a51-49b2-a3b6-063b5595003d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')&quot;)]</value>
      <webElementGuid>89b9e8b3-4f43-4238-aa8a-3ffa844b92c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>c25a0093-5b51-4882-b3e3-19d7c864fb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucCreditProcessMainInfo_lbAppNo' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ucCreditProcessMainInfo$lbAppNo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '539APP20240200145' or . = '539APP20240200145')]</value>
      <webElementGuid>ba533c3d-cd31-4d63-ae49-960218d04435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
