<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Copy Address</name>
   <tag></tag>
   <elementGuidId>2b9709d3-76d7-4a38-bb73-57d422d561f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Form_CopyAddr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_CopyAddr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e513949-bf9d-4edd-8d5f-c09c713e5979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_CopyAddr</value>
      <webElementGuid>2d211219-7e83-4be4-a24f-99949b51a3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91cd5eb8-2a49-499a-a9de-fab8df704e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_CopyAddr&quot;, &quot;&quot;, true, &quot;vgCopyAddr&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>5dc3477f-6ba2-40c4-a032-c13f1ba6bb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy Address</value>
      <webElementGuid>c5f166e2-e2cc-4ce8-a094-cc2f7e08004d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Form_CopyAddr&quot;)</value>
      <webElementGuid>a884cc66-4dc0-4532-8d8f-13dc6b236dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>feb64a12-6854-4700-905b-e1ea8e3e2c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Form_CopyAddr']</value>
      <webElementGuid>ab7fd16d-3cc8-4363-9187-7a898e0fbe00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMailingAddr']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>53eecd7b-7979-41b3-9747-10bfc1fc0fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Copy Address')]</value>
      <webElementGuid>af9791c0-ca3c-4ae1-ad7d-f7da9ebfcc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Address From'])[1]/following::a[1]</value>
      <webElementGuid>f11fec51-bda6-42e7-a5f3-838df6e1d6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mailing Address'])[1]/following::a[1]</value>
      <webElementGuid>9de1e3da-9be4-4ea8-8217-b9494c5b7579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::a[1]</value>
      <webElementGuid>4567b35c-6de5-434a-87d1-f576a44da207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::a[1]</value>
      <webElementGuid>dd264d90-b205-4228-8b26-4411a85b42db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy Address']/parent::*</value>
      <webElementGuid>086d5bfe-572e-4da8-a31c-d17026abd20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_CopyAddr&quot;, &quot;&quot;, true, &quot;vgCopyAddr&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>4c509700-01fa-45a0-a9cb-74753edc7473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>2e2c4cb1-e737-4cb0-ad54-380ec4723921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Form_CopyAddr' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_CopyAddr&quot;, &quot;&quot;, true, &quot;vgCopyAddr&quot;, &quot;&quot;, false, true))' and (text() = 'Copy Address' or . = 'Copy Address')]</value>
      <webElementGuid>5d2662bd-8c29-4377-b5d6-675d8cc809f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
