<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Term  Condition_appForm</name>
   <tag></tag>
   <elementGuidId>299e7af5-74c1-4169-9f28-35341574380c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='appForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#appForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b0f6e086-2ac6-4899-9082-3bcc9394ac1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ApplicationData/AppDataX.aspx?AppId=1631938&amp;AppSrc=</value>
      <webElementGuid>f9a7d176-c285-40a3-abb8-05b560b21b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>ccbe4d98-3829-4aa8-83c4-6e86df5e83bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>a0f0e695-585a-473d-b4bf-513a225767d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa025440-ff3a-449b-ba58-60400598f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appForm&quot;)</value>
      <webElementGuid>3a880a81-dc83-44ba-b55a-5b0533620999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>07fe2b84-07f8-49aa-9272-5d9fc83bfeb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='appForm']</value>
      <webElementGuid>0f1ff67c-838a-4777-a717-4b6f65e8af11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appFormContainer']/iframe</value>
      <webElementGuid>2d95abbd-7c64-4628-94b8-6a2adaf286c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0450ce82-af77-4385-8ac3-073324d8aec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ApplicationData/AppDataX.aspx?AppId=1631938&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>6a2c02c9-e667-4856-b05c-e6d0fcadca14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ApplicationData/AppDataX.aspx?AppId=1631940&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>ef1c360e-1523-4f52-91d7-07b4d30c5591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ApplicationData/AppDataX.aspx?AppId=1631824&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>cc44e946-e4bd-4050-8d16-469fe02762bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/ApplicationData/AppDataX.aspx?AppId=1631900&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>85af6abe-dea3-4bae-b536-70920e464993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
