<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Tenor</name>
   <tag></tag>
   <elementGuidId>eb03bfa4-bd49-4fdf-ad0e-feed0e769b57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINTenor_txtInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucINTenor_txtInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b249263e-2146-424d-8aac-10d03621c978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINTenor$txtInput</value>
      <webElementGuid>ec8c38e2-f42c-4d59-b761-60b6d5d84399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc226d6c-edb7-4b9f-b2cf-d5e1bb98fb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9466e98c-1c01-4229-bedf-7e1ce5d6bf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINTenor$txtInput\',\'\')', 0)</value>
      <webElementGuid>6bfc633b-8219-4886-bded-aea99f168551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>ab7deb11-6784-486d-820e-2b454e1fd89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINTenor_txtInput</value>
      <webElementGuid>f2131c37-1824-488f-aec6-b85fd2a1095d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>0ca8d3f2-83a1-4b7b-9e6c-3270154e07fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return (event.keyCode!=13);</value>
      <webElementGuid>77926c1d-6a68-4e53-8016-8e6409ecacfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValueInteger('ucINTenor_txtInput','ucINTenor_hdnInput','ucINTenor_txtInputDummy');</value>
      <webElementGuid>e01b26b1-247d-4d05-928d-6a1a9167fb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINTenor_txtInput');</value>
      <webElementGuid>e630070b-2fa6-41b6-ba1a-54a31967a382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINTenor_txtInput&quot;)</value>
      <webElementGuid>848f3f5f-fa55-4d39-90f6-264a5b52e2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>41948d6c-d93b-43ef-8866-44017c9a1d5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINTenor_txtInput']</value>
      <webElementGuid>a9577374-aba7-4fac-80fe-34bef25282f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAppData']/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>f7f40366-af3f-4dfe-9034-5311522c88f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>29e241ac-9985-4f8b-af17-271051a18382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINTenor$txtInput' and @type = 'text' and @id = 'ucINTenor_txtInput']</value>
      <webElementGuid>baf67d1a-4ef7-48ec-98a3-9e1da561f73e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
